# MySQL 配置
[mysql]
host = 192.168.200.131
user = root
password = 12345678
database = subjects_kg

# Redis 配置
[redis]
host = 192.168.200.131
port = 6379
password =
db = 0

# Milvus 配置
[milvus]
host = 192.168.200.131
port = 19530
database_name = itcast
collection_name = edurag_0421

# LLM 配置
[llm]
model = qwen3-max
dashscope_api_key = sk-ws-H.EYIEMIL.KYTl.MEYCIQClBozIyZPwfL5NWnQboWEnuFIei-e8Bp4s75AjgW7jCAIhAMyRlKG2VNaYkAXqsix9HVcbUhnnogFNcIXWLf30L8zl
dashscope_base_url = https://ws-swpj97bw00gfqcg8.cn-beijing.maas.aliyuncs.com/compatible-mode/v1

# 检索参数配置
[retrieval]
parent_chunk_size = 500
child_chunk_size = 100
chunk_overlap = 20
retrieval_k = 3
candidate_m = 2

# 日志配置
[logger]
log_file = /Users/P72/PycharmProjects/AsIf/Itcast_qa_system/logs/app.log

# 应用配置
[app]
valid_sources = ["ai", "java", "test", "ops", "bigdata"]
customer_service_phone = 12345678