version: '3.8'

services:
  mysql:
    image: mysql:8.0.43
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: function_calls
      MYSQL_USER: vincent
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    command: --local-infile=1
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data: